export enum DbCollection {
  users = 'users',
  projects = 'projects',
  organizations = 'organizations',
  tasks = 'tasks',
  taskHistory = 'task-history',
  taskTimeLog = 'task-time-log',
  taskType = 'task-type',
  taskStatus = 'task-status',
  taskPriority = 'task-priority',
  taskComments = 'task-comments',
  sprint = 'sprint',
  sprintReports = 'sprint-reports',
  attachments = 'attachments',
  invitations = 'invitations',
  resetPassword = 'reset-password',
  workflow = 'workflow',
  board = 'board',
  userRole = 'user-role'
}
