export enum EmailSubjectEnum {
  projectInvitation = 'Project Invitation',
  resetPassword = 'Reset Password',
  changePassword = 'Password Changed',
  sprintPublished = 'A new sprint published',
  sprintClosed = 'Sprint Closed',
  taskMoved = 'Task moved to a column',
  taskAssigned = ':displayName assigned to me',
  taskUpdated = ':userName Updated :displayName',
  taskCreated = 'Task Created',
  taskCommentAdded = 'Comment Added',
  taskCommentUpdated = 'Comment Updated',
  taskCommentPinned = 'Comment Pinned',
  taskCommentUnPinned = 'Comment Un-Pinned',
}
